name: "Futuri LDR1 Discovery"
description: ""
url: "http://futuri-discovery.tigerking.nyc"
sass:
    sass_dir: assets/stylesheets/
exclude: ['Gruntfile.js', 'node_modules', 'package.json']
gems:
  - jekyll-redirect-from
collections:
  instant_request_services:
    output: true
  interfaces:
    output: true
